### ISSUE TITLE
punctuation is removed

### ISSUE THREAD

**Issue by solsticedhiver** [mrgnhnt96/change_case#2]
The  functions have problem with punctuations or even apostrophe

Example:

    "WE'RE ALMOST HERE.".toCapitalCase() // "We Re Almost Here"
    "WE'RE ALMOST HERE".toSentenceCase() // "We re almost here"
    "WE'RE ALMOST HERE".toTitlelCase() // "WE'RE ALMOST HERE."

I would except the punctuation to stay, and stay the same.

**Comment by mrgnhnt96** [comment]
Hey @solsticedhiver 👋 

Thanks for bringing this to my attention, I'll work on a fix for this
